components/FileUploadS3.jsx
components/admin/CreateProjectForm.jsx
components/admin/DeleteProjectForm.jsx
components/admin/EditProjectForm.jsx
components/admin/EditUserForm.jsx
components/admin/Home.jsx
components/admin/Sidenav.jsx
components/dashboard/AssetList.jsx
components/dashboard/AssetModal.jsx
pages/admin/[admin_form_name].jsx
pages/admin/index.jsx

- login form
- home page
- edit user
- create project
- edit project
- delete project
- 404
- validation for all forms
- error alerts and success modals
- image upload to public s3 bucket for create and edit projects
- Extend admin panel for user, whitelist and team management

:add: admin panel ui /admin

---

components/PaginatedTable.jsx
components/admin/EditProjectForm.jsx
pages/projects/[project_id].jsx
pages/projects/index.jsx

:add: collapsable paginated list for /admin/edit_project

---

pages/whitelist.jsx

- checkboxes work correctly
- button is enabled only for correct time frame and before being sold out

:update: connect with api/whitelist

---

components/admin/EditProjectForm.jsx
pages/projects/index.jsx

:patch: fix GET projects api call

---

pages/admin/index.jsx
pages/exchange.jsx
pages/purchase.jsx
pages/refund.jsx

- API integration for purchase and exchange pages
- create assembler url redirect from backend ```/api/assembler/return/{wallet}/{smartContract}```

Add token exchange and refund page

---

pages/exchange.jsx
pages/purchase.jsx

- ### tests for pending transactions
- ### hits new allowance endpoint
- ### hits new vesting/vest endpoint
- enable submit button at correct time
- handle response from api/vesting/vest (show amounts for token and ergs)

:update: purchase

---

components/admin/CreateProjectForm.jsx
components/admin/EditProjectForm.jsx
components/admin/EditUserForm.jsx
pages/exchange.jsx
pages/purchase.jsx

:updates: submit form for exchange and purchase

---

components/dashboard/VestingTable.jsx
pages/dashboard.jsx
pages/exchange.jsx

:update: fetch data for vesting table in dashboard

---

pages/exchange.jsx
pages/purchase.jsx

:update: bug fixes for exchange and purchase

---

pages/exchange.jsx
pages/purchase.jsx

- :update: /purchase modal text
- make qr code larger for desktop
- issue still exists with mobile screens (qr too small to be read)

:update: /purchase modal message and fix qr code

---

pages/exchange.jsx
pages/purchase.jsx

:update: automate submit button timer

---

pages/exchange.jsx
pages/purchase.jsx

:fix: infinite loop bug

---

components/admin/CreateProjectForm.jsx
components/admin/EditProjectForm.jsx
pages/exchange.jsx
pages/projects/[project_id].jsx

- ### small fix for admin projects page (still need to check backend)
- ### update exchange page transaction wait time to 5 mins

:update: assembler wait time for exchange

---

pages/purchase.jsx

- fix presale subtitle text
- remove toEarly text (apiCheck() call will display text only if too early)

:fix: text strategic -> presale

---

components/dashboard/AssetItem.jsx
components/dashboard/StackedAreaPortfolioHistory.jsx
pages/dashboard.jsx

- ### Empty Screen
- ### Desktop
- ### Mobile
- ### Need to wait till backend ```api/asset/price/history/{coin}``` is deployed live
- ### Change to weekly timeframe once aggregator has collected enough data
```
// CONFIG for portfolio history
// step size
const STEP_SIZE = 1;
// step unit is hours
// todo: (switch to weeks once we have enough data)
const STEP_UNIT = 'h';
```

:add: price history graph in dashboard

---

package.json
pages/projects/[project_id].jsx

- markdown
- render
- react-markdown (basic support)
- react-gfm (plugin for full markdown support)
- unist-util-visit-parents dependency for react-gfm

add: markdown support

---

pages/projects/[project_id].jsx

:fix: markdown styles

---

components/PaginatedTable.jsx
components/admin/CreateJobForm.jsx
components/admin/DeleteJobForm.jsx
components/admin/EditJobForm.jsx
components/admin/Sidenav.jsx
pages/admin/[admin_form_name].jsx

- ### Create
- ### Edit
- ### Delete
- Depends on https://github.com/ergo-pad/ergopad/pull/111

:add: Job Listings Admin Page

---

pages/careers/[job_id].jsx
pages/careers/index.jsx

- ```/careers```
- ```/careers/id```
- Fix placeholder subtitle
- Add /careers to page footers
- Add How to apply text

:add: careers page

---

pages/exchange.jsx

- removed alignment state
https://github.com/ergo-pad/ergopad/issues/115

:fix: exchange bug

---

pages/dashboard.jsx

:add: async dashboard

---

components/dashboard/AssetModal.jsx
components/dashboard/PieChart.jsx
components/dashboard/StackedAreaPortfolioHistory.jsx
pages/dashboard.jsx

:add: average effective price in dashboard modal

---

components/dashboard/PriceChart.jsx
components/landing/Dashboard.jsx
pages/dashboard.jsx

:add: dashboard  chart

---

components/dashboard/PriceChart.jsx
components/dashboard/StackedAreaPortfolioHistory.jsx

https://github.com/FormidableLabs/victory/issues/414

:fix: alignment in dashboard stackedarea and line charts

---

components/AddWallet.jsx

Dapp connect

---

components/AddWallet.jsx
components/PaginatedTable.jsx
utils/AddWalletContext.js

- auto reconnect to wallet on new session
- pagination buttons only show when required i.e when number of rows > 5.

:improve: ux for add wallet

---

components/AddWallet.jsx
pages/dashboard.jsx
utils/WalletContext.js

Assets and Vesting
- Manual Testing: add addresses to ```const walletAddresses``` list line: 276 dashboard.jsx to test for correctness

# Wallet Aggregation

---

pages/projects/index.jsx

:add: project page named url

---

components/dashboard/StakingTable.jsx
components/dashboard/VestingTable.jsx
pages/dashboard.jsx

- ### Sample Data
- ### No Data

:add: staking table

---

components/landing/Projects.jsx
components/layout/Footer.jsx
pages/projects/index.jsx
pages/whitelist.jsx

- project url for landing page updated

:add: paideia whitelist

---

components/AddWallet.jsx
components/staking/StakingRewardsBox.jsx
components/staking/StakingSummary.jsx
components/staking/StakingTiers.jsx
components/staking/UnstakingFeesTable.jsx
components/staking/UnstakingTable.jsx
pages/staking.jsx
utils/AddWalletContext.js

- Change to real ErgoPad tokens after testing phase
- Fix Decimal issues (backend)
- Add caching to /api/status (backend)

Staking v1

---

pages/projects/[project_id].jsx

:fix: markdown muilink

---

pages/whitelist.jsx

:fix: whitelist error message

---

components/staking/StakingRewardsBox.jsx
components/staking/StakingSummary.jsx
components/staking/TransactionSubmitted.jsx
components/staking/UnstakingTable.jsx
pages/staking.jsx

- ### Unstaking penalty calculated by frontend
- ### Circular progress spinners for loading
- ### Unstake max button
- ### Transaction submitted view

:update: staking ux

---

pages/staking.jsx

- ### Token ID changed to real ERGOPAD token
- ### Token balance updated when stake modal is opened
- ### Code Formatted
- ### Changed get_utxos from minimum 0.001 ergs to 0.01 ergs

:update: final staking updates

---

components/dashboard/PieChart.jsx
components/dashboard/StackedAreaPortfolioHistory.jsx
components/dashboard/StakingTable.jsx
pages/dashboard.jsx

:update: aggregate locked in dashboard

---

components/dashboard/VestingTable.jsx
pages/dashboard.jsx

:fix: improves dashboard

---

components/layout/Footer.jsx
pages/careers/[job_id].jsx
pages/projects/[project_id].jsx

:update: careers placeholder text

---

components/admin/CreateAnnouncementForm.jsx
components/admin/CreateFaqForm.jsx
components/admin/CreateProjectForm.jsx
components/admin/DeleteAnnouncementForm.jsx
components/admin/DeleteFaqForm.jsx
components/admin/EditAnnouncementForm.jsx
components/admin/EditFaqForm.jsx
components/admin/EditProjectForm.jsx
components/admin/Sidenav.jsx
pages/admin/[admin_form_name].jsx
pages/faq.jsx

-
-
-
-
-
- Will be added in a seperate PR after we have some announcements created

:update: CMS

---

components/dashboard/StackedAreaPortfolioHistory.jsx
components/token/PriceChart.jsx
pages/dashboard.jsx
pages/whitelist.jsx

- updated to show 12 weeks of data instead 6 weeks
- renamed Ergopad -> ErgoPad

:update: whitelist form

---

pages/contribute.jsx
pages/dashboard.jsx
pages/whitelist.jsx

- works only with SAFEW (as of now)
- on page refresh need to remove wallet and reconnect for safew to connect correctly
- change token ids before deployment (PROXY NFT, WHITELIST TOKENS)
- line 162: ```setFormState(formOpenState.OPEN); // change to CLOSED```
- whitelist page prevent 0 SigUSD value
- Dashboard charts: ```vested``` -> ```vesting```

:add: dapp /contribute (beta)

---

pages/contribute.jsx

:update: constants for /contribute

---

components/dashboard/TokenRedeemModal.jsx
components/dashboard/VestingTable.jsx
pages/dashboard.jsx

- Desktop
- Mobile
- ### dapp connector for redeem

:add: vestingWithNFT table to dashboard

---

components/TransactionSubmitted.jsx
components/dashboard/TokenRedeemModal.jsx
components/dashboard/VestingTable.jsx
pages/contribute.jsx
pages/dashboard.jsx

- ### dapp integration for redeem
- ### refactored transaction submitted component to reduce code duplication
closes #103

:add: vesting redeem to dashboard

---

components/dashboard/TokenRedeemModal.jsx
components/dashboard/VestingTable.jsx
components/landing/Dashboard.jsx
components/landing/Projects.jsx
components/token/PriceChart.jsx
pages/contribute/paideia/seed.jsx

:fix: undefined access error in contribute page

---

components/ListTextInput.jsx
components/admin/GenerateWhitelistEventReportForm.jsx
package.json
pages/admin/[admin_form_name].jsx
pages/whitelist/[projectName]/[roundName].jsx

:add: export to csv for whitelist

---

pages/contribute/paideia/strategic.jsx

:update: contribute form text

---

components/dashboard/TokenRedeemModal.jsx
pages/contribute/paideia/strategic.jsx

:add: ergopay redeem

---

components/admin/CreateWhitelistEventForm.jsx
components/admin/EditWhitelistEventForm.jsx
pages/dashboard.jsx
pages/whitelist/[projectName]/[roundName].jsx

:add: staker snapshot whitelist

---

pages/contribute/[projectName]/[roundName].jsx

- fix NaN tokens remaining
- fix padding on mobile

:update: contribute form

---

components/ListTextInput.jsx
components/layout/Footer.jsx
components/projects/Team.jsx
pages/dashboard.jsx
pages/projects/[project_id].jsx

- show sum in the circular pie chart for vesting tokens (if price is available)
- closes #143
- update to admin panel
- projects page
- closes #141
- closes #136

:update: frontend

---

components/dashboard/StackedAreaPortfolioHistory.jsx

:fix: responsive design for portfolio history

---

styles/globals.css

:fix: overflow on iOS devices

---

components/admin/EditUserForm.jsx
components/admin/Sidenav.jsx
components/dashboard/PieChart.jsx
pages/contribute/[projectName]/[roundName].jsx

- Change password tab
- Dashboard

:update: cms user privileges

---

components/AddWallet.jsx

:fix: dapp wallet popup

---

components/AddWallet.jsx

:fix: dapp connector

---

components/layout/Layout.jsx
styles/globals.css

:fix: sticky projects

---

components/layout/Layout.jsx

:fix: transparency issue on homepage

---

components/NotificationBell.jsx

:update: notification ttl

---

components/dashboard/TokenRedeemModal.jsx
pages/contribute/[projectName]/[roundName].jsx

- ### updates for new redeem and contribute endpoints

:update: contribute and redeem

---

pages/staking.jsx

:remove: dapp get_utxos

---

components/AutoCompleteSelect.jsx
components/admin/CreateTutorialForm.jsx
components/admin/DeleteTutorialForm.jsx
components/admin/EditTutorialForm.jsx
components/admin/Sidenav.jsx
pages/admin/[admin_form_name].jsx
pages/guides.jsx

- ### Create/Edit/Delete Tutorials
- ### Categories - add new categories or select from existing ones
- ### Upload custom banner or ability to pull banner from YouTube
- ### Filter by categories or search

:add: tutorials and guides

---

components/admin/CreateStakingConfigForm.jsx
components/admin/DeleteStakingConfigForm.jsx
components/admin/EditStakingConfigForm.jsx
components/admin/Sidenav.jsx
pages/admin/[admin_form_name].jsx

:add: cms staking-v2 admin pages

---

components/admin/CreateStakingConfigForm.jsx
components/admin/EditStakingConfigForm.jsx

:add: tokenDecimals to admin staking-config forms

---

components/dashboard/StakingTable.jsx
pages/dashboard.jsx

- depends on https://github.com/ergo-pad/ergopad-api/pull/237

:add: staking-v2 to dashboard

---

components/ListTextInput.jsx

:add: clear profile pic image

---

components/admin/CreateStakingConfigForm.jsx
components/admin/EditStakingConfigForm.jsx
components/landing/Dashboard.jsx
components/staking/UnstakingTable.jsx
pages/announcements/[announcement_id].jsx
pages/staking/[project_id].jsx

- configure staking v1 from cms

:add: staking v1 cms update

---

pages/staking/[project_id].jsx

:fix: staking ergio bugs

---

components/dashboard/StakingTable.jsx
pages/dashboard.jsx

- replace with single `/staking/staked-all` call

:update: dashboard staked call

---

pages/dashboard.jsx

:add: staked switch

---

components/admin/CreateStakingConfigForm.jsx
components/admin/EditStakingConfigForm.jsx
components/staking/UnstakingTable.jsx
pages/staking/[project_id].jsx
pages/staking/index.jsx

:disable: egio staking

---

pages/token.jsx

- consume https://ergopad.io/api/blockchain/tokenomics/d71693c49a84fbbecd4908c94813b46514b18b67a99952dc1e6e4791556de413

:update: /token to use optimized endpoint

---

pages/dashboard.jsx

- https://github.com/ergo-pad/ergopad-api/issues/369

:add: dashboard danaides

---

pages/contribute/[projectName]/[roundName].jsx
pages/staking/[project_id].jsx
pages/staking/index.jsx

:remove: references to explorer for balances

---

pages/contribute/[projectName]/[roundName].jsx
pages/dashboard.jsx
pages/staking/[project_id].jsx
pages/staking/index.jsx

Update balance endpoint

---

components/layout/Footer.jsx
hooks/useContributionProjects.ts
hooks/useWhitelistProjects.ts
package.json
pages/contribute/[projectName]/[roundName].jsx
pages/projects/[project_id].jsx
utils/axios.ts

Added link to round at project page

---

.editorconfig
.eslintrc.json
components/projects/ActiveProjectCard.jsx
components/projects/ProjectCard.jsx
hooks/useProjectInfo.ts
pages/projects/index.jsx

Added active section at projects page

---

hooks/useContributionProjects.ts
hooks/useWhitelistProjects.ts

:fix: client side error

---

components/landing/ActiveRound.jsx

```
Application error: a client-side exception has occurred (see the browser console for more information).
```
- load `ergopad.io/staking` or any other page without going to homepage (`ergopad.io`) first
- click ergopad icon to redirect to homepage

:fix: client side undefined ref error

---

components/AddWallet.jsx
utils/WalletContext.js

- Support for individual wallets using `ergoConnector`
- Nautilus an SafeW added

:update: wallet model to use ergoConnector

---

components/AddWallet.jsx

:fix: add wallet modal alignment

---

components/admin/CreateWhitelistEventForm.jsx
components/admin/EditWhitelistEventForm.jsx
pages/whitelist/[projectName]/[roundName].jsx

- frontend changes for https://github.com/ergo-pad/ergopad-api/issues/436

:update: automate early bird round

---

pages/dashboard.jsx
utils/LogoMapper.js

- partial fix for https://github.com/ergo-pad/ergopad-api/issues/440

:update: optimize dashboard explorer call

---

pages/dashboard.jsx

- ergopad vesting is completed as of 27/09/2022

Removes vesting/v1 call

---

components/admin/CreateProjectForm.jsx
components/admin/DeleteProjectForm.jsx
components/admin/EditProjectForm.jsx

:update: project as draft

---

pages/whitelist/[projectName]/[roundName].jsx

- Issue: https://github.com/ergo-pad/ergopad-api/issues/548
- Depends on https://github.com/ergo-pad/ergopad-api/pull/569

:update: staker whitelist with sigUSD value

---

components/dashboard/AssetItem.jsx
components/dashboard/AssetModal.jsx
pages/dashboard.jsx

:add: audio nft logo

---

pages/token.jsx

Change "ergodex" to "spectrum"
